### ISSUE TITLE
Vertical divider (sometimes) can't be moved

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#206] opened 2021-11-18 13:08 UTC

**Comment by ethteck** [comment] 2021-12-20 16:08
I can't ever move it on the live site but I can locally sometimes. I haven't been able to narrow it down further, sorry :/

**Comment by nanaian** [comment] 2021-12-30 13:10
Caused by #205, closing in favour of that issue

**Closed by nanaian** 2021-12-30 13:10 UTC
Labels: bug, frontend, high priority
