### ISSUE TITLE
Make the website not implode when it goes down

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#719] opened 2023-03-28 04:54 UTC
<img width="437" alt="image" src="https://user-images.githubusercontent.com/2985314/228131920-051c2ce2-1943-4f24-89b6-4d9e5db74b58.png">
Pages should hopefully still stay up, and we should maybe warn the user to not navigate away while the site is updating. Instead, pages insatntly change to this yucky error, and so all progress is lost. very unfortunate if you're editing a scratch

**Comment by nanaian** [comment] 2023-03-28 05:31
#617

**Comment by nanaian** [comment] 2023-06-03 13:33
Duplicate of #617

**Closed by nanaian** 2023-06-03 13:33 UTC
Labels: bug, frontend, high priority
