### ISSUE TITLE
Branch arrow naught invisible when using the default color scheme on light mode

### ISSUE THREAD

**Issue by mid-kid** [decompme/decomp.me#788] opened 2023-06-19 10:44 UTC
![imatge](https://github.com/decompme/decomp.me/assets/1339276/80d458ea-b8fa-4aae-8dce-196ffd0b1d1d)

**Comment by marijnvdwerf** [comment] 2023-06-19 18:58
Duplicate of #678 and #757

**Closed by marijnvdwerf** 2023-06-19 18:58 UTC
Labels: frontend
