### ISSUE TITLE
[BUG] Sorting by "Most matched" can show 0% scratches at the top of the list

### ISSUE THREAD

**Issue by ethteck** [decompme/decomp.me#1249] opened 2024-05-20 10:45 UTC
https://decomp.me/preset/1 present here

![image](https://github.com/decompme/decomp.me/assets/2985314/4c33c55c-0886-4488-96f4-7c861de785b0)

**Comment by edmondsoun** [comment] 2024-08-20 23:26
It looks like this specific bug is being caused by the DB setting a default score of -1, which then will always sort these to the top for "Most Matched". (It acts the same in reverse, scratches with scores of -1 end up at the very bottom when sorted by "Least Matched".)

I can quickly fix this on the frontend by sorting the results of the API call (using `produceSortFunction`/`compareScratchScores` that already exist over in `Sort.tsx`) or can dig a bit deeper into the backend and see about customizing ordering on the queryset so no changes would be necessary on the frontend. Any preference from y'all? 🙂

**Comment by ethteck** [comment] 2024-08-22 03:21
Hey, thanks for looking at this @edmondsoun ! I believe the best thing to do here would be to just handle it on the frontend as you suggest :)

**Comment by mkst** [comment] 2024-09-12 07:30
whilst that PR was merged and released, I'm still seeing issues with ordering
![image](https://github.com/user-attachments/assets/a0261a4d-f31b-465c-9a88-934b1263c83e)

**Comment by ethteck** [comment] 2024-09-12 07:32
I don't think it was intended to have been fixed yet, since the issue is still open. I could be wrong

**Comment by mkst** [comment] 2024-09-15 12:25
I feel like this could be solved via something like https://www.pixiebrix.com/blog/sort-django-queryset-by-custom-order/ where we add a Case for the -1 score to be Infinity (or some equivalent) so the sorting can be done on the database side - because client-side sorting won't properly work with pagination.

**Closed** 2024-09-21 20:37 UTC
Labels: bug, frontend
