### ISSUE TITLE
Ability to customised assembler flags

### ISSUE THREAD

**Issue by mkst** [decompme/decomp.me#574] opened 2022-10-28 16:31 UTC
A handful of the compilers (e.g. PSYQ) compile `.c` -> `.s` -> `.o`, e.g.
```
PSYQ_CC = 'cpp -P "$INPUT" | unix2dos | ${WINE} ${COMPILER_DIR}/CC1PSX.EXE -quiet ${COMPILER_FLAGS} -o "$OUTPUT".s && ${WINE} ${COMPILER_DIR}/ASPSX.EXE -quiet "$OUTPUT".s -o "$OUTPUT".obj && ${COMPILER_DIR}/psyq-obj-parser "$OUTPUT".obj -o "$OUTPUT"'
```

I would like to be able to pass `-G8` to the assembler for functions that reference `sdata`. I cannot add the flag to the default compiler command because this affects codegen.

Tasks:
- [ ] determine what the steps are
- [ ] add backend support
- [ ] add frontend support
- [ ] add database migration (TBD whether any presets have explicit assembly flags set, if not, then this should be very simple)
- [ ] what else?

**Comment by ethteck** [comment] 2022-10-28 16:39
related to #142 too

**Comment by nanaian** [comment] 2022-10-30 17:08
Duplicate of #142

**Closed by nanaian** 2022-10-30 17:08 UTC
Labels: duplicate
